### ISSUE TITLE
Database does not exist

### ISSUE THREAD

**Issue by yuriaps** [adriantanasa/connect-cloudant-store#8]
I created a db with some name lets say mydb
I put the url that was on the service credentials, dont know how it will choose the db...

got this error using the debbuger:

connect:cloudant-store DATABASE does not exists {"message":"Database does not exist.","stack":"Error: Database does not exist.\n    at Object.clientCallback (/Users/yuriaps/Downloads/02a-simple-node-web-app/node_modules/nano/lib/nano.js:154:15)\n    at Request._callback (/Users/yuriaps/Downloads/02a-simple-node-web-app/node_modules/@cloudant/cloudant/lib/clientutils.js:164:11)\n    at Request.self.callback (/Users/yuriaps/Downloads/02a-simple-node-web-app/node_modules/request/request.js:185:22)\n    at emitTwo (events.js:126:13)\n    at Request.emit (events.js:214:7)\n    at Request.self._source.emit (/Users/yuriaps/Downloads/02a-simple-node-web-app/node_modules/@cloudant/cloudant/lib/eventrelay.js:78:21)\n    at Request.<anonymous> (/Users/yuriaps/Downloads/02a-simple-node-web-app/node_modules/request/request.js:1161:10)\n    at emitOne (events.js:116:13)\n    at Request.emit (events.js:211:7)","name":"Error","error":"not_found","reason":"Database does not exist.","scope":"couch","statusCode":404,"request":{"method":"GET","headers":{"content-type":"application/json","accept":"application/json"},"uri":"https://XXXXXX:XXXXXX@f31513c4-2efc-4001-95ee-f65fe790ae80-bluemix.cloudantnosqldb.appdomain.cloud/sessions","qsStringifyOptions":{"arrayFormat":"repeat"}},"headers":{"uri":"https://XXXXXX:XXXXXX@f31513c4-2efc-4001-95ee-f65fe790ae80-bluemix.cloudantnosqldb.appdomain.cloud/sessions","statusCode":404,"cache-control":"must-revalidate","content-type":"application/json","date":"Wed, 31 Jul 2019 02:15:41 GMT","x-couch-request-id":"e54da078ff","x-frame-options":"ALLOW-FROM https://f31513c4-2efc-4001-95ee-f65fe790ae80-bluemix.cloudantnosqldb.appdomain.cloud","strict-transport-security":"max-age=31536000","x-content-type-options":"nosniff","x-cloudant-request-class":"unlimited","x-cloudant-backend":"bm-cc-us-south-13","via":"1.1 lb1.bm-cc-us-south-13 (Glum/1.81.0)"},"errid":"non_200","description":"couch returned 404"} +0ms

**Comment by yuriaps** [comment]
Now I understood, I HAVE TO CREATE A DB CALLED SESSIONS....

**Comment by akshaymattoo** [comment]
Thank you @yuriaps i was also not able to figure out what is the issue as I had created a different name db.
